services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command:
      [
        "uvicorn", 
        "main:app", 
        "--host", 
        "0.0.0.0", 
        "--port", 
        "8080"
      ]